// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildServiceEntities(ModelBuilder modelBuilder) {
    modelBuilder.Entity("ServiFinance.Domain.Assignment", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("AssignedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("AssignedUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("AssignmentStatus")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("ScheduledEndUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("ScheduledStartUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("ServiceRequestId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("AssignedByUserId");

            b.HasIndex("AssignedUserId");

            b.HasIndex("ServiceRequestId");

            b.HasIndex("TenantId");

            b.ToTable("Assignments", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.AssignmentEvent", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("AssignedUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("AssignmentId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("AssignmentStatus")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<Guid>("ChangedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<Guid?>("PreviousAssignedUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime?>("PreviousScheduledEndUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("PreviousScheduledStartUtc")
                .HasColumnType("datetime2");

            b.Property<string>("Remarks")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<DateTime?>("ScheduledEndUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("ScheduledStartUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("AssignedUserId");

            b.HasIndex("AssignmentId");

            b.HasIndex("ChangedByUserId");

            b.HasIndex("PreviousAssignedUserId");

            b.HasIndex("TenantId");

            b.ToTable("AssignmentEvents", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.AssignmentEvidence", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("AssignmentId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("ContentType")
                .HasMaxLength(120)
                .HasColumnType("nvarchar(120)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("Note")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("nvarchar(2000)");

            b.Property<string>("OriginalFileName")
                .HasMaxLength(260)
                .HasColumnType("nvarchar(260)");

            b.Property<string>("RelativeUrl")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("StoredFileName")
                .HasMaxLength(260)
                .HasColumnType("nvarchar(260)");

            b.Property<Guid>("SubmittedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("AssignmentId");

            b.HasIndex("SubmittedByUserId");

            b.HasIndex("TenantId");

            b.ToTable("AssignmentEvidence", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.Customer", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Address")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("CustomerCode")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("FullName")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<string>("MobileNumber")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("TenantId");

            b.HasIndex("TenantId", "CustomerCode")
                .IsUnique();

            b.ToTable("Customers", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.ServiceRequest", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("CreatedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("CurrentStatus")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("FeedbackComments")
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<string>("IssueDescription")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<string>("ItemDescription")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("ItemType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("Priority")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<int?>("Rating")
                .HasColumnType("int");

            b.Property<string>("RequestNumber")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime?>("RequestedServiceDate")
                .HasColumnType("datetime2");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("CreatedByUserId");

            b.HasIndex("CustomerId");

            b.HasIndex("TenantId");

            b.HasIndex("TenantId", "RequestNumber")
                .IsUnique();

            b.ToTable("ServiceRequests", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.StatusLog", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("ChangedAtUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("ChangedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Remarks")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<Guid>("ServiceRequestId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("ChangedByUserId");

            b.HasIndex("ServiceRequestId");

            b.HasIndex("TenantId");

            b.ToTable("StatusLogs", (string)null);
        });

    }
  }
}
