// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildRelationships(ModelBuilder modelBuilder) {
    modelBuilder.Entity("ServiFinance.Domain.AmortizationSchedule", b =>
        {
            b.HasOne("ServiFinance.Domain.MicroLoan", "MicroLoan")
                .WithMany("AmortizationSchedules")
                .HasForeignKey("MicroLoanId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("MicroLoan");
        });

    modelBuilder.Entity("ServiFinance.Domain.AppUser", b =>
        {
            b.HasOne("ServiFinance.Domain.Tenant", "Tenant")
                .WithMany("Users")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Tenant");
        });

    modelBuilder.Entity("ServiFinance.Domain.Assignment", b =>
        {
            b.HasOne("ServiFinance.Domain.AppUser", "AssignedByUser")
                .WithMany("CreatedAssignments")
                .HasForeignKey("AssignedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.AppUser", "AssignedUser")
                .WithMany("AssignedAssignments")
                .HasForeignKey("AssignedUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.ServiceRequest", "ServiceRequest")
                .WithMany("Assignments")
                .HasForeignKey("ServiceRequestId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("AssignedByUser");

            b.Navigation("AssignedUser");

            b.Navigation("ServiceRequest");
        });

    modelBuilder.Entity("ServiFinance.Domain.AssignmentEvent", b =>
        {
            b.HasOne("ServiFinance.Domain.AppUser", "AssignedUser")
                .WithMany()
                .HasForeignKey("AssignedUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Assignment", "Assignment")
                .WithMany("Events")
                .HasForeignKey("AssignmentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.AppUser", "ChangedByUser")
                .WithMany("AssignmentEvents")
                .HasForeignKey("ChangedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.AppUser", "PreviousAssignedUser")
                .WithMany()
                .HasForeignKey("PreviousAssignedUserId")
                .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("AssignedUser");

            b.Navigation("Assignment");

            b.Navigation("ChangedByUser");

            b.Navigation("PreviousAssignedUser");
        });

    modelBuilder.Entity("ServiFinance.Domain.AssignmentEvidence", b =>
        {
            b.HasOne("ServiFinance.Domain.Assignment", "Assignment")
                .WithMany("EvidenceItems")
                .HasForeignKey("AssignmentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.AppUser", "SubmittedByUser")
                .WithMany("AssignmentEvidenceItems")
                .HasForeignKey("SubmittedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Assignment");

            b.Navigation("SubmittedByUser");
        });

    modelBuilder.Entity("ServiFinance.Domain.Customer", b =>
        {
            b.HasOne("ServiFinance.Domain.Tenant", "Tenant")
                .WithMany("Customers")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Tenant");
        });

    modelBuilder.Entity("ServiFinance.Domain.Invoice", b =>
        {
            b.HasOne("ServiFinance.Domain.Customer", "Customer")
                .WithMany("Invoices")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.ServiceRequest", "ServiceRequest")
                .WithMany("Invoices")
                .HasForeignKey("ServiceRequestId")
                .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("Customer");

            b.Navigation("ServiceRequest");
        });

    modelBuilder.Entity("ServiFinance.Domain.InvoiceLine", b =>
        {
            b.HasOne("ServiFinance.Domain.Invoice", "Invoice")
                .WithMany("InvoiceLines")
                .HasForeignKey("InvoiceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Invoice");
        });

    modelBuilder.Entity("ServiFinance.Domain.LedgerTransaction", b =>
        {
            b.HasOne("ServiFinance.Domain.AmortizationSchedule", "AmortizationSchedule")
                .WithMany("Transactions")
                .HasForeignKey("AmortizationScheduleId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("ServiFinance.Domain.AppUser", "CreatedByUser")
                .WithMany("CreatedTransactions")
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Customer", "Customer")
                .WithMany("Transactions")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Invoice", "Invoice")
                .WithMany("Transactions")
                .HasForeignKey("InvoiceId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("ServiFinance.Domain.MicroLoan", "MicroLoan")
                .WithMany("Transactions")
                .HasForeignKey("MicroLoanId")
                .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("AmortizationSchedule");

            b.Navigation("CreatedByUser");

            b.Navigation("Customer");

            b.Navigation("Invoice");

            b.Navigation("MicroLoan");
        });

    modelBuilder.Entity("ServiFinance.Domain.MicroLoan", b =>
        {
            b.HasOne("ServiFinance.Domain.AppUser", "CreatedByUser")
                .WithMany("CreatedMicroLoans")
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Customer", "Customer")
                .WithMany("MicroLoans")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Invoice", "Invoice")
                .WithOne("MicroLoan")
                .HasForeignKey("ServiFinance.Domain.MicroLoan", "InvoiceId")
                .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("CreatedByUser");

            b.Navigation("Customer");

            b.Navigation("Invoice");
        });

    modelBuilder.Entity("ServiFinance.Domain.RefreshSession", b =>
        {
            b.HasOne("ServiFinance.Domain.Customer", "Customer")
                .WithMany()
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("ServiFinance.Domain.AppUser", "User")
                .WithMany("RefreshSessions")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("Customer");

            b.Navigation("User");
        });

    modelBuilder.Entity("ServiFinance.Domain.Role", b =>
        {
            b.HasOne("ServiFinance.Domain.Tenant", "Tenant")
                .WithMany("Roles")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Tenant");
        });

    modelBuilder.Entity("ServiFinance.Domain.ServiceRequest", b =>
        {
            b.HasOne("ServiFinance.Domain.AppUser", "CreatedByUser")
                .WithMany("CreatedServiceRequests")
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Customer", "Customer")
                .WithMany("ServiceRequests")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("CreatedByUser");

            b.Navigation("Customer");
        });

    modelBuilder.Entity("ServiFinance.Domain.StatusLog", b =>
        {
            b.HasOne("ServiFinance.Domain.AppUser", "ChangedByUser")
                .WithMany("StatusLogs")
                .HasForeignKey("ChangedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.ServiceRequest", "ServiceRequest")
                .WithMany("StatusLogs")
                .HasForeignKey("ServiceRequestId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("ChangedByUser");

            b.Navigation("ServiceRequest");
        });

    modelBuilder.Entity("ServiFinance.Domain.SubscriptionTierModule", b =>
        {
            b.HasOne("ServiFinance.Domain.PlatformModule", "PlatformModule")
                .WithMany("TierAssignments")
                .HasForeignKey("PlatformModuleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.SubscriptionTier", "SubscriptionTier")
                .WithMany("Modules")
                .HasForeignKey("SubscriptionTierId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("PlatformModule");

            b.Navigation("SubscriptionTier");
        });

    modelBuilder.Entity("ServiFinance.Domain.TenantBillingRecord", b =>
        {
            b.HasOne("ServiFinance.Domain.AppUser", "SubmittedByUser")
                .WithMany("SubmittedBillingRecords")
                .HasForeignKey("SubmittedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.Tenant", "Tenant")
                .WithMany("BillingRecords")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("SubmittedByUser");

            b.Navigation("Tenant");
        });

    modelBuilder.Entity("ServiFinance.Domain.TenantTheme", b =>
        {
            b.HasOne("ServiFinance.Domain.Tenant", "Tenant")
                .WithOne("Theme")
                .HasForeignKey("ServiFinance.Domain.TenantTheme", "TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Tenant");
        });

    modelBuilder.Entity("ServiFinance.Domain.UserRole", b =>
        {
            b.HasOne("ServiFinance.Domain.Role", "Role")
                .WithMany("UserRoles")
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("ServiFinance.Domain.AppUser", "User")
                .WithMany("UserRoles")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Role");

            b.Navigation("User");
        });

    }
  }
}
