// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildIdentityEntities(ModelBuilder modelBuilder) {
    modelBuilder.Entity("ServiFinance.Domain.AppUser", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("FullName")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<bool>("IsActive")
                .HasColumnType("bit");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique();

            b.HasIndex("TenantId");

            b.ToTable("Users", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.RefreshSession", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<Guid?>("CustomerId")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime>("LastRotatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("RefreshTokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<bool>("RememberMe")
                .HasColumnType("bit");

            b.Property<string>("Surface")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<Guid?>("UserId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("CustomerId");

            b.HasIndex("ExpiresAtUtc");

            b.HasIndex("RefreshTokenHash")
                .IsUnique();

            b.HasIndex("UserId");

            b.ToTable("RefreshSessions", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.Role", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("TenantId");

            b.HasIndex("TenantId", "Name")
                .IsUnique();

            b.ToTable("Roles", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.UserRole", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("AssignedAtUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("RoleId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("UserId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("RoleId");

            b.HasIndex("TenantId");

            b.HasIndex("UserId");

            b.HasIndex("TenantId", "UserId", "RoleId")
                .IsUnique();

            b.ToTable("UserRoles", (string)null);
        });

    }
  }
}
