// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildCatalogEntities(ModelBuilder modelBuilder) {
    modelBuilder.Entity("ServiFinance.Domain.PlatformModule", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Channel")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<bool>("IsActive")
                .HasColumnType("bit");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("nvarchar(150)");

            b.Property<int>("SortOrder")
                .HasColumnType("int");

            b.Property<string>("Summary")
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnType("nvarchar(300)");

            b.HasKey("Id");

            b.HasIndex("Code")
                .IsUnique();

            b.ToTable("ModuleCatalog", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.SubscriptionTier", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("AudienceSummary")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<string>("BillingLabel")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("BusinessSizeSegment")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("HighlightLabel")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<bool>("IncludesMicroLendingDesktop")
                .HasColumnType("bit");

            b.Property<bool>("IncludesServiceManagementWeb")
                .HasColumnType("bit");

            b.Property<bool>("IsActive")
                .HasColumnType("bit");

            b.Property<string>("PlanSummary")
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnType("nvarchar(300)");

            b.Property<string>("PriceDisplay")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<int>("SortOrder")
                .HasColumnType("int");

            b.Property<string>("SubscriptionEdition")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.HasKey("Id");

            b.HasIndex("Code")
                .IsUnique();

            b.ToTable("SubscriptionTiers", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.SubscriptionTierModule", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("AccessLevel")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("nvarchar(30)");

            b.Property<Guid>("PlatformModuleId")
                .HasColumnType("uniqueidentifier");

            b.Property<int>("SortOrder")
                .HasColumnType("int");

            b.Property<Guid>("SubscriptionTierId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("PlatformModuleId");

            b.HasIndex("SubscriptionTierId", "PlatformModuleId")
                .IsUnique();

            b.ToTable("SubscriptionTierModules", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.Tenant", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("BusinessSizeSegment")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("DomainSlug")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<bool>("IsActive")
                .HasColumnType("bit");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<string>("SubscriptionEdition")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("SubscriptionPlan")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("SubscriptionStatus")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.HasKey("Id");

            b.HasIndex("Code")
                .IsUnique();

            b.HasIndex("DomainSlug")
                .IsUnique();

            b.ToTable("Tenants", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.TenantTheme", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("DisplayName")
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<string>("HeaderBackgroundColor")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<string>("LogoUrl")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("PageBackgroundColor")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<string>("PrimaryColor")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<string>("SecondaryColor")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("TenantId")
                .IsUnique();

            b.ToTable("TenantThemes", (string)null);
        });

    }
  }
}
