// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildFinanceEntities(ModelBuilder modelBuilder) {
    modelBuilder.Entity("ServiFinance.Domain.AmortizationSchedule", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("BeginningBalance")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<DateTime>("DueDate")
                .HasColumnType("datetime2");

            b.Property<decimal>("EndingBalance")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("InstallmentAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<int>("InstallmentNumber")
                .HasColumnType("int");

            b.Property<string>("InstallmentStatus")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<decimal>("InterestPortion")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid>("MicroLoanId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("PaidAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("PrincipalPortion")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("TenantId");

            b.HasIndex("MicroLoanId", "InstallmentNumber")
                .IsUnique();

            b.ToTable("AmortizationSchedules", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.Invoice", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("DiscountAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("InterestableAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<DateTime>("InvoiceDateUtc")
                .HasColumnType("datetime2");

            b.Property<string>("InvoiceNumber")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("InvoiceStatus")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<decimal>("OutstandingAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid?>("ServiceRequestId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("SubtotalAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("TotalAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.HasKey("Id");

            b.HasIndex("CustomerId");

            b.HasIndex("ServiceRequestId");

            b.HasIndex("TenantId");

            b.HasIndex("TenantId", "InvoiceNumber")
                .IsUnique();

            b.ToTable("Invoices", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.InvoiceLine", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<Guid>("InvoiceId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("LineTotal")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("Quantity")
                .HasPrecision(10, 2)
                .HasColumnType("decimal(10,2)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("UnitPrice")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.HasKey("Id");

            b.HasIndex("InvoiceId");

            b.HasIndex("TenantId");

            b.ToTable("InvoiceLines", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.LedgerTransaction", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<Guid?>("AmortizationScheduleId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("CreatedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("CreditAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("DebitAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid?>("InvoiceId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid?>("MicroLoanId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("ReferenceNumber")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("Remarks")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<decimal>("RunningBalance")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("TransactionDateUtc")
                .HasColumnType("datetime2");

            b.Property<string>("TransactionType")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.HasKey("Id");

            b.HasIndex("AmortizationScheduleId");

            b.HasIndex("CreatedByUserId");

            b.HasIndex("CustomerId");

            b.HasIndex("InvoiceId");

            b.HasIndex("MicroLoanId");

            b.HasIndex("TenantId");

            b.ToTable("Transactions", (string)null);
        });

    modelBuilder.Entity("ServiFinance.Domain.MicroLoan", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("AnnualInterestRate")
                .HasPrecision(6, 2)
                .HasColumnType("decimal(6,2)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("CreatedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid?>("InvoiceId")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("LoanStartDate")
                .HasColumnType("datetime2");

            b.Property<string>("LoanStatus")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime>("MaturityDate")
                .HasColumnType("datetime2");

            b.Property<decimal>("MonthlyInstallment")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("PrincipalAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.Property<int>("TermMonths")
                .HasColumnType("int");

            b.Property<decimal>("TotalInterestAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("TotalRepayableAmount")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.HasKey("Id");

            b.HasIndex("CreatedByUserId");

            b.HasIndex("CustomerId");

            b.HasIndex("InvoiceId")
                .IsUnique()
                .HasFilter("[InvoiceId] IS NOT NULL");

            b.HasIndex("TenantId");

            b.ToTable("MicroLoans", (string)null);
        });

    }
  }
}
