// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildNavigations(ModelBuilder modelBuilder) {
    modelBuilder.Entity("ServiFinance.Domain.AmortizationSchedule", b =>
        {
            b.Navigation("Transactions");
        });

    modelBuilder.Entity("ServiFinance.Domain.AppUser", b =>
        {
            b.Navigation("AssignedAssignments");

            b.Navigation("AssignmentEvents");

            b.Navigation("AssignmentEvidenceItems");

            b.Navigation("CreatedAssignments");

            b.Navigation("CreatedMicroLoans");

            b.Navigation("CreatedServiceRequests");

            b.Navigation("CreatedTransactions");

            b.Navigation("RefreshSessions");

            b.Navigation("StatusLogs");

            b.Navigation("SubmittedBillingRecords");

            b.Navigation("UserRoles");
        });

    modelBuilder.Entity("ServiFinance.Domain.Assignment", b =>
        {
            b.Navigation("Events");

            b.Navigation("EvidenceItems");
        });

    modelBuilder.Entity("ServiFinance.Domain.Customer", b =>
        {
            b.Navigation("Invoices");

            b.Navigation("MicroLoans");

            b.Navigation("ServiceRequests");

            b.Navigation("Transactions");
        });

    modelBuilder.Entity("ServiFinance.Domain.Invoice", b =>
        {
            b.Navigation("InvoiceLines");

            b.Navigation("MicroLoan");

            b.Navigation("Transactions");
        });

    modelBuilder.Entity("ServiFinance.Domain.MicroLoan", b =>
        {
            b.Navigation("AmortizationSchedules");

            b.Navigation("Transactions");
        });

    modelBuilder.Entity("ServiFinance.Domain.PlatformModule", b =>
        {
            b.Navigation("TierAssignments");
        });

    modelBuilder.Entity("ServiFinance.Domain.Role", b =>
        {
            b.Navigation("UserRoles");
        });

    modelBuilder.Entity("ServiFinance.Domain.ServiceRequest", b =>
        {
            b.Navigation("Assignments");

            b.Navigation("Invoices");

            b.Navigation("StatusLogs");
        });

    modelBuilder.Entity("ServiFinance.Domain.SubscriptionTier", b =>
        {
            b.Navigation("Modules");
        });

    modelBuilder.Entity("ServiFinance.Domain.Tenant", b =>
        {
            b.Navigation("BillingRecords");

            b.Navigation("Customers");

            b.Navigation("Roles");

            b.Navigation("Theme");

            b.Navigation("Users");
        });
    }
  }
}
