// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  partial class ServiFinanceDbContextModelSnapshot {
    private void BuildBillingEntities(ModelBuilder modelBuilder) {
      modelBuilder.Entity("ServiFinance.Domain.TenantBillingRecord", b =>
          {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<decimal>("AmountDue")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<decimal>("AmountSubmitted")
                .HasPrecision(12, 2)
                .HasColumnType("decimal(12,2)");

            b.Property<string>("BillingPeriodLabel")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<DateTime>("CoverageEndUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime>("CoverageStartUtc")
                .HasColumnType("datetime2");

            b.Property<DateTime>("DueDateUtc")
                .HasColumnType("datetime2");

            b.Property<string>("Note")
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<string>("PaymentMethod")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("ProofContentType")
                .HasMaxLength(120)
                .HasColumnType("nvarchar(120)");

            b.Property<string>("ProofOriginalFileName")
                .HasMaxLength(260)
                .HasColumnType("nvarchar(260)");

            b.Property<string>("ProofRelativeUrl")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("ProofStoredFileName")
                .HasMaxLength(260)
                .HasColumnType("nvarchar(260)");

            b.Property<string>("ReferenceNumber")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("ReviewRemarks")
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<DateTime?>("ReviewedAtUtc")
                .HasColumnType("datetime2");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime>("SubmittedAtUtc")
                .HasColumnType("datetime2");

            b.Property<Guid>("SubmittedByUserId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("TenantId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("SubmittedByUserId");

            b.HasIndex("TenantId");

            b.HasIndex("TenantId", "DueDateUtc");

            b.ToTable("TenantBillingRecords", (string)null);
          });
    }
  }
}
