// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ServiFinance.Infrastructure.Data;

#nullable disable

namespace ServiFinance.Infrastructure.Migrations {
  [DbContext(typeof(ServiFinanceDbContext))]
  partial class ServiFinanceDbContextModelSnapshot : ModelSnapshot {
    protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.5")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      BuildFinanceEntities(modelBuilder);
      BuildIdentityEntities(modelBuilder);
      BuildServiceEntities(modelBuilder);
      BuildCatalogEntities(modelBuilder);
      BuildRelationships(modelBuilder);
      BuildNavigations(modelBuilder);
#pragma warning restore 612, 618
    }
  }
}
